### ISSUE TITLE
Faild to start plists_service (iPhoneX or newer)

### ISSUE THREAD

**Issue by chrisfxs** [iOSForensics/pymobiledevice#19]
I have used the code to build a project to transfer the files to iPhone from Windows.It works on the iPhone 8 or any older one .But it faild on iPhoneX or any newer one.
hope for any help
thank you!

**Comment by chrisfxs** [comment]
There are the error messages:
`Traceback (most recent call last):
  File "PullLogFolder.py", line 11, in <module>
    result, msg = MobileCore.PullLogFolder(platform)
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\MobileCore.py", line 236, in PullLogFolder
    errCode, msg = iOSHelper.PullLogFiles(logDir)
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\iOSHelper.py", line 95, in PullLogFiles
    service = lockdown_client.startService("com.apple.mobile.house_arrest")
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\pymobiledevice\lockdown.py", line 301, in startService
    return PlistService(StartService.get("Port"), self.udid)
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\pymobiledevice\plist_service.py", line 46, in __init__
    self.connect(udid)
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\pymobiledevice\plist_service.py", line 54, in connect
    mux.process(1.0)
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\pymobiledevice\usbmux\usbmux.py", line 251, in process
    self.listener.process(timeout)
  File "D:\work\CG_Trank\CJGame\trunk\Survive\ExternalTools\pymobiledevice\usbmux\usbmux.py", line 216, in process
    rlo, wlo, xlo = select.select([self.socket.sock], [], [self.socket.sock], timeout)
KeyboardInterrupt`

**Comment by chrisfxs** [comment]
I supposes that the problem is the new iPhone like iPhone XR has a different UUID format.

**Comment by GotoHack** [comment]
Sorry I do not have any iPhone XR around. Can you run lockdown.py alone and provide me the full crash trace ?

**Comment by chenqb** [comment]
@chrisfxs I've fix this problem ,  plist_service.py line 57: if d.serial == udid.replace('-','') 。
on iphoneX or newer, there is a '-' in udid string.

**Comment by chenqb** [comment]
@GotoHack  I've tested pass ,you can merge it .
plist_service.py line 57: if d.serial == udid.replace('-','')

**Comment by chenqb** [comment]
> I supposes that the problem is the new iPhone like iPhone XR has a different UUID format.

yes , u r right . there is a '-' in udid string on iPhoneX or newer. I've fix it. please see downstair.

**Comment by GotoHack** [comment]
The commit cc9af40 should fix the problem.
Does anyone is able to test before merging on master ?
Connect you iPhoneX or newer 

Test procedure:
$ git clone https://github.com/iOSForensics/pymobiledevice
$ git fetch -a
$ git checkout -b mre/fix-udid 
$ python lockdown.py

Thank you!
