### ISSUE TITLE
pydeviceinfo error

### ISSUE THREAD

**Issue by beckietech** [iOSForensics/pymobiledevice#38]
This is really great work! after successfully installed, I type pydeviceinfo, pylockdown...etc. when I type in pydeviceinfo, I got following:
pydeviceinfo 
Traceback (most recent call last):
  File "/usr/local/bin/pydeviceinfo", line 33, in <module>
    sys.exit(load_entry_point('pymobiledevice==1.3.0', 'console_scripts', 'pydeviceinfo')())
  File "/usr/local/bin/pydeviceinfo", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pymobiledevice.ideviceinfo'

Can I know what am I missing? Thanks

**Comment by GotoHack** [comment]
fixed by  commit a11f0dc (removing missing dep)
